version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "frontend"

  # Enable version updates for Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "docker"

  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "backend"

  # Enable version updates for Python dependencies in image-generation-service
  - package-ecosystem: "pip"
    directory: "/image-generation-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "image-generation-service"

  # Enable version updates for Python dependencies in rag_model_service
  - package-ecosystem: "pip"
    directory: "/rag_model_service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "rag-model-service"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"