# Configuration for the labeler action
# https://github.com/actions/labeler

# Frontend related changes
frontend:
  - 'frontend/**/*'
  - 'frontend/*'

# Backend related changes  
backend:
  - 'backend/**/*'
  - 'backend/*'

# API Gateway related changes
api-gateway:
  - 'api_gateway/**/*'
  - 'api_gateway/*'

# Image Generation Service related changes
image-generation:
  - 'image-generation-service/**/*'
  - 'image-generation-service/*'

# RAG Model Service related changes
rag-model:
  - 'rag_model_service/**/*'
  - 'rag_model_service/*'

# Chrome Extension related changes
extension:
  - 'ai-assistant-extension/**/*'
  - 'ai-assistant-extension/*'

# Documentation changes
documentation:
  - '**/*.md'
  - 'docs/**/*'
  - '*.md'

# GitHub Actions and workflows
github-actions:
  - '.github/**/*'
  - '.github/workflows/*'

# Docker related changes
docker:
  - '**/Dockerfile'
  - 'docker-compose.yml'
  - 'docker-compose.*.yml'

# Dependencies
dependencies:
  - 'package.json'
  - 'package-lock.json'
  - 'requirements.txt'
  - 'Pipfile'
  - 'Pipfile.lock'
  - 'yarn.lock'

# Configuration files
config:
  - '**/*.env*'
  - '**/*.config.*'
  - '.gitignore'
  - '.dockerignore'

# Security related
security:
  - 'SECURITY.md'
  - '**/*security*'
  - '**/*auth*'

# Testing
testing:
  - '**/*test*'
  - '**/*spec*'
  - '**/test/**/*'
  - '**/tests/**/*'

# Bug fix
bug:
  - any:
    - title: '/fix|bug|issue/'
    - body: '/fix|bug|issue/'

# Enhancement  
enhancement:
  - any:
    - title: '/feature|enhancement|improve/'
    - body: '/feature|enhancement|improve/'