version: '3.8'

services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "8080:8080"
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    networks:
      - app_network
    depends_on:
      - image-generation-service
      - rag-model-service

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - backend

  image-generation-service:
    build: ./image-generation-service
    ports:
      - "8000:8000"
    env_file:
      - ./image-generation-service/.env
    networks:
      - app_network

  rag-model-service:
    build: ./rag_model_service
    ports:
      - "8081:8081"
    env_file:
      - ./rag_model_service/.env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
